# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ablum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ablum_name', models.CharField(max_length=200)),
                ('ablum_no', models.IntegerField()),
                ('ablum_pic', models.URLField()),
                ('ablum_des', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_no', models.IntegerField()),
                ('pic_url', models.URLField()),
                ('pic_text', models.CharField(max_length=200)),
                ('ablum_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bl.Ablum')),
            ],
        ),
    ]
