# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ablum',
            name='ablum_no',
            field=models.CharField(max_length=20),
        ),
    ]
