# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0002_auto_20180626_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic_no',
            field=models.CharField(max_length=200),
        ),
    ]
